spring.application.name=BatchProcessor


# Oracle DB connection
spring.datasource.url=jdbc:oracle:thin:@exarac2u-scan.rhbgroup.com:1528:IISSIT
spring.datasource.username=UAT1389448PIDM
spring.datasource.password=IISsit##2025
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

api.key.header=X-API-KEY
api.key.value=my-secret-key


data.file.path=classpath:data.txt
